version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true # This helps with hot-reloading in some environments

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000

