# Dockerfile.backend
FROM node:18

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

COPY . ./

COPY ./docker-entrypoint.sh /app/
RUN chmod +x /app/docker-entrypoint.sh
CMD ["/app/docker-entrypoint.sh"]
